# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rosebiology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binomial_nomenclature', models.CharField(max_length=200)),
                ('height_and_spread', models.CharField(max_length=100)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'roses',
                'permissions': (('display_details_roses_', 'Can view details of a Species'),),
            },
        ),
    ]
